# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :run_unit_tests do
    gradle(task: "testDebugUnitTest --stacktrace")
  end

  desc "Runs all the tests with coverage"
  lane :testDev do
    gradle(task: "pixel2api30DebugAndroidTest testDebugUnitTest jacocoTestReport --stacktrace")
  end

  desc "Deploy to Firebase AppTester channel"
  lane :distDev do
    gradle(task: "generateKsPropFile generateGoogleServicesJson generateAppDistKey clean assembleDebug")
    firebase_app_distribution(
        service_credentials_file: ENV['APP_DIST_SERVICE_ACCOUNT_PATH'],
        app: "1:1032339097117:android:1e333da555ec74a71668f4",
        groups: "testers",
        release_notes: "",
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
